services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - RAILS_ENV=development
    tty: true
    stdin_open: true
    entrypoint: ./entrypoint.dev.sh
    command: bundle exec puma -C config/puma.rb
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  
  tailwind:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    command: rails tailwindcss:watch
    stdin_open: true
    tty: true
